broken arm

diff --git a/_bashrc b/_bashrc
--- a/_bashrc
+++ b/_bashrc
@@ -1,143 +1,40 @@
-#
 # ~/.bashrc
-
 
 [[ $- != *i* ]] && return
 
-source ~/.bash-prompt
+function shload {
+    local s="$(realpath -m ~/.bash.d/$1)"
+    local b="$(basename -s .SH -- ${s^^})"
+    local -n v="SHLOAD_${b//[^a-zA-Z0-9]/_}"
+    if [[ -e "$s" ]]; then
+        source "$s" "${@:2}"
+        v="$?"
+    else
+        echo "shload: $s not found at line $(caller)" >&2
+        v=-1
+    fi
+}
 
-#colors() {
-#    local fgc bgc vals seq0
-#
-#    printf "Color escapes are %s\n" "\e[${value};...;${value}m"
-#    printf "Values 30..37 are \e[33mforeground colors\e[m\n"
-#    printf "Values 40..47 are \e[43mbackground colors\e[m\n"
-#    printf "Value  1 gives a  \e[1mbold-faced look\e[m\n\n"
-#
-#    # foreground colors
-#    for fgc in {30..37}; do
-#        # background colors
-#        for bgc in {40..47}; do
-#            fgc=${fgc#37} # white
-#            bgc=${bgc#40} # black
-#
-#            vals="${fgc:+$fgc;}${bgc}"
-#            vals=${vals%%;}
-#
-#            seq0="${vals:+\e[${vals}m}"
-#            printf "  %-9s" "${seq0:-(default)}"
-#            printf " ${seq0}TEXT\e[m"
-#            printf " \e[${vals:+${vals+$vals;}}1mBOLD\e[m"
-#        done
-#        echo; echo
-#    done
-#}
+shload bash-saveline.sh
+# shload bash-mdirs.sh
 
 [ -r /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion
-
-# Change the window title of X terminals
-#case ${TERM} in
-#	xterm*|rxvt*|Eterm*|aterm|kterm|gnome*|interix|konsole*)
-#		PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\007"'
-#		;;
-#	screen*)
-#		PROMPT_COMMAND='echo -ne "\033_${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\033\\"'
-#		;;
-#esac
-
-# Set colorful PS1 only on colorful terminals.
-# dircolors --print-database uses its own built-in database
-# instead of using /etc/DIR_COLORS.  Try to use the external file
-# first to take advantage of user additions.  Use internal bash
-# globbing instead of external grep binary.
-safe_term=${TERM//[^[:alnum:]]/?}   # sanitize TERM
-match_lhs=""
-[[ -f ~/.dir_colors   ]] && match_lhs="${match_lhs}$(<~/.dir_colors)"
-[[ -f /etc/DIR_COLORS ]] && match_lhs="${match_lhs}$(</etc/DIR_COLORS)"
-[[ -z ${match_lhs}    ]] \
-    && type -P dircolors >/dev/null \
-    && match_lhs=$(dircolors --print-database)
-[[ $'\n'${match_lhs} == *$'\n'"TERM "${safe_term}* ]] && use_color=true
-
-# Enable colors for ls, etc.  Prefer ~/.dir_colors #64489
-if type -P dircolors >/dev/null ; then
-    if [[ -f ~/.dir_colors ]] ; then
-        eval $(dircolors -b ~/.dir_colors)
-    elif [[ -f /etc/DIR_COLORS ]] ; then
-        eval $(dircolors -b /etc/DIR_COLORS)
-    fi
-fi
 
 alias grep='grep --colour=auto'
 alias egrep='egrep --colour=auto'
 alias fgrep='fgrep --colour=auto'
 
-unset use_color safe_term match_lhs
-
-#xhost +local:root > /dev/null 2>&1
-
-# Bash won't get SIGWINCH if another process is in the foreground.
-# Enable checkwinsize so that bash will check the terminal size when
-# it regains control.  #65623
-# http://cnswww.cns.cwru.edu/~chet/bash/FAQ (E11)
-shopt -s checkwinsize
-
-shopt -s expand_aliases
-
-# export QT_SELECT=4
-
-# Enable history appending instead of overwriting.  #139609
-shopt -s histappend
-
-#
-# # ex - archive extractor
-# # usage: ex <file>
-ex ()
-{
-  if [ -f $1 ] ; then
-    case $1 in
-      *.tar.bz2)   tar xjf $1   ;;
-      *.tar.gz)    tar xzf $1   ;;
-      *.bz2)       bunzip2 $1   ;;
-      *.rar)       unrar x $1     ;;
-      *.gz)        gunzip $1    ;;
-      *.tar)       tar xf $1    ;;
-      *.tbz2)      tar xjf $1   ;;
-      *.tgz)       tar xzf $1   ;;
-      *.zip)       unzip $1     ;;
-      *.Z)         uncompress $1;;
-      *.7z)        7z x $1      ;;
-      *)           echo "'$1' cannot be extracted via ex()" ;;
-   esac
-  else
-    echo "'$1' is not a valid file"
-  fi
-}
-
-#color_prompt=yess
-#. /usr/share/bash-conf/themes/box_blue
-
+set -o ignoreeof
+shopt -s checkwinsize expand_aliases
 
 export PAGER=less
 export LESS='-RFXi'
 
 HISTSIZE=50000
 SAVEHIST=50000
-HISTIGNORE=exuit:bg:fg:history:pwd
+HISTIGNORE=exit:bg:fg:history:pwd:jobs
 HISTCONTROL=ignoreboth
 shopt -s histappend
-
-
-#bcp() { echo "copying $1 to $1-bak"; cp -r "$1" "${1}-bak"; }
-
-##
-## displaycolors for 256- and ascii-color modes
-##
-colorwall() {
-  for i in {0..255}; do
-    print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'};
-  done
-}
 
 #function _emacspick {
 #  if [[ -S /var/run/user/${UID}/emacs/server ]]; then
@@ -146,11 +43,6 @@ colorwall() {
 #    emacs "$@"
 #  fi
 #}
-export EDITOR=vim
-export VISUAL=vim
-alias vi=vim
-alias v=vim
-#alias emacs=_emacspick
 
 # high dpi -- fractional currently broken
 #export GDK_SCALE=1.25
@@ -158,15 +50,16 @@ alias v=vim
 
 # somne in zsh these are getting overwriten so have to come after
 #alias lsbase='exa --group-directories-first --color=always'
-lsbase() {
-  exa --group-directories-first --color=always -s=Name -Fh "$@"
-}
-alias ls='lsbase --grid -aa -s=Name'
-alias ll='lsbase --icons --git --extended --long'
-alias la='lsbase --icons --git -aa'
-alias lw='lsbase --grid'
+#function lsbase {
+#  exa --group-directories-first --color=always -s=Name -Fh "$@"
+#}
+alias _lsb='exa --group-directories-first --color=always -s=Name -Fh'
+alias ls='_lsb --grid'
+alias ll='_lsb --icons --git --extended --long'
+alias la='_lsb --icons --git -aa'
+alias lw='_lsb --grid'
 alias lla='ll -aa'
-alias lwa='lw -aa'
+alias lwa='ls --grid -aa'
 
 alias kk='kde-open'
 
@@ -178,14 +71,27 @@ qtlog () {
   "$@"
 }
 
-# pnpm
-export PNPM_HOME="/home/jason/.local/share/pnpm"
-export PATH="$PNPM_HOME:~/.emacs.d/bin:$PATH"
-# pnpm end
+export EDITOR=vim
+export VISUAL=vim
+alias vi=vim
+alias v=vim
 
+#alias emacs=_emacspick
+alias eec="vim ~/.doom.d/config.el"
+alias vvc='vim ~/.bashrc'
+
+alias pp=pushd
+alias px=popd
+
+export PNPM_HOME="/home/jason/.local/share/pnpm"
 export GOPATH=~/go
 
-stty -ixon
+export PATH="~/bin:~/.local/bin:$PNPM_HOME:~/.emacs.d/bin:$PATH"
 
+alias n='ninja -j 1 -k 1 -C ~/cdev/dts/build/ -f build-Debug.ninja'
+
+shload bash-prompt.sh
+
+stty -ixon
 
 
